apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-service-d
spec:
  selector:
    matchLabels:
      app: books-service-p
  replicas: 3
  template:
    metadata:
      labels:
        app: books-service-p
    spec:
      containers:
        - name: books-service-c
          image: marcoiza/books-service:v4
          # imagePullPolicy: Never
          ports:
            - containerPort: 8000